In [28]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt

plt.rc('figure', figsize = (20, 8))

df = pd.read_csv('data/FIFA_2018_Statistics.csv')
df.head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,NaN,NaN
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,NaN,Group Stage,No,0,NaN,NaN
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,No,NaN,Group Stage,No,0,NaN,NaN
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,Yes,89.0,Group Stage,No,0,NaN,NaN
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,No,NaN,Group Stage,No,0,1.0,90.0

## Removendo Valores Faltantes

* Observe que alguns valores estão com NaN (Not a Number)
* A olho nu, provavelmente não conseguiríamos visualizar todos os casos.
* utilizaremos a função *isnull* que retorna um DataFrame com valores booleanos que apontam as ocorrências de valores faltantes.
* obs.: a função *notnull()* faz o contrário:

In [29]:
df.isnull().head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

* Uma maneira de quantificar os valores faltantes é usando o **isnull().sum()**

In [30]:
df.isnull().sum()

Date                        0
Team                        0
Opponent                    0
Goal Scored                 0
Ball Possession %           0
Attempts                    0
On-Target                   0
Off-Target                  0
Blocked                     0
Corners                     0
Offsides                    0
Free Kicks                  0
Saves                       0
Pass Accuracy %             0
Passes                      0
Distance Covered (Kms)      0
Fouls Committed             0
Yellow Card                 0
Yellow & Red                0
Red                         0
Man of the Match            0
1st Goal                   34
Round                       0
PSO                         0
Goals in PSO                0
Own goals                 116
Own goal Time             116
dtype: int64

### Melhorando a visualização

In [31]:
valores_faltantes = df.isnull().sum().sort_values(ascending = False)
percentual_valores_faltantes = (valores_faltantes/df.shape[0])*100
#col_names = ['Valores Faltantes', '% Valores Faltantes']
#pd.concat([valores_faltantes, percentual_valores_faltantes], axis = 1, keys = col_names)
df_vf = pd.concat([valores_faltantes, percentual_valores_faltantes], axis = 1)
df_vf.columns = ['Valores Faltantes', '% Valores Faltantes']
df_vf

                        Valores Faltantes  % Valores Faltantes
Own goal Time                         116              90.6250
Own goals                             116              90.6250
1st Goal                               34              26.5625
Free Kicks                              0               0.0000
Team                                    0               0.0000
Opponent                                0               0.0000
Goal Scored                             0               0.0000
Ball Possession %                       0               0.0000
Attempts                                0               0.0000
On-Target                               0               0.0000
Off-Target                              0               0.0000
Blocked                                 0               0.0000
Corners                                 0               0.0000
Offsides                                0               0.0000
Pass Accuracy %                         0               0.0000
Saves                                   0               0.0000
Passes                                  0               0.0000
Distance Covered (Kms)                  0               0.0000
Fouls Committed                         0               0.0000
Yellow Card                             0               0.0000
Yellow & Red                            0               0.0000
Red                                     0               0.0000
Man of the Match                        0               0.0000
Round                                   0               0.0000
PSO                                     0               0.0000
Goals in PSO                            0               0.0000
Date                                    0               0.0000

### Eliminando valores faltantes - função dropna()

* Podemos eliminar as linhas com NaN na coluna Valor utilizando a função **dropna**
* Podemos usamos o parâmetro **subset**, onde definimos em quais colunas devem ser eliminadas os valores faltantes.

In [32]:
df_new = df.dropna(subset=['1st Goal', 'Own goals', 'Own goal Time'])
df_new.isnull().sum()

Date                      0
Team                      0
Opponent                  0
Goal Scored               0
Ball Possession %         0
Attempts                  0
On-Target                 0
Off-Target                0
Blocked                   0
Corners                   0
Offsides                  0
Free Kicks                0
Saves                     0
Pass Accuracy %           0
Passes                    0
Distance Covered (Kms)    0
Fouls Committed           0
Yellow Card               0
Yellow & Red              0
Red                       0
Man of the Match          0
1st Goal                  0
Round                     0
PSO                       0
Goals in PSO              0
Own goals                 0
Own goal Time             0
dtype: int64

## Interpolação

Podemos fazer interpolação no pandas usando o parâmetro **method** da função **fillna()**.

### Exemplo 1 - method ffill
* Preenche com os valores das linhas acima (começa de cima para baixo).
* É utilizado principalmente em séries temporais

In [33]:
df_new = df.fillna(method='ffill')
df_new[['Team', 'Opponent', 'Goal Scored', '1st Goal', 'Own goals', 'Own goal Time']].head()

           Team      Opponent  Goal Scored  1st Goal  Own goals  Own goal Time
0        Russia  Saudi Arabia            5      12.0        NaN            NaN
1  Saudi Arabia        Russia            0      12.0        NaN            NaN
2         Egypt       Uruguay            0      12.0        NaN            NaN
3       Uruguay         Egypt            1      89.0        NaN            NaN
4       Morocco          Iran            0      89.0        1.0           90.0

### Exemplo 2 - method bfill
* Preenche com os valores das linhas abaixo (começa de baixo para cima).
* É utilizado principalmente em séries temporais

In [34]:
df_new = df.fillna(method='bfill')
df_new[['Team', 'Opponent', 'Goal Scored', '1st Goal', 'Own goals', 'Own goal Time']].head()

           Team      Opponent  Goal Scored  1st Goal  Own goals  Own goal Time
0        Russia  Saudi Arabia            5      12.0        1.0           90.0
1  Saudi Arabia        Russia            0      89.0        1.0           90.0
2         Egypt       Uruguay            0      89.0        1.0           90.0
3       Uruguay         Egypt            1      89.0        1.0           90.0
4       Morocco          Iran            0      90.0        1.0           90.0

### Exemplo 3 - usando a média da coluna
* Preenche com a média dos registros da coluna

In [35]:
'''
df_new = df
df_new.fillna(value={
    '1st Goal': df_new['1st Goal'].mean(),
    'Own goals': df_new['Own goals'].mean(),
    'Own goal Time': df_new['Own goal Time'].mean(),
}, inplace=True)
'''

df_new = df.fillna(df.mean())


df_new[['Team', 'Opponent', 'Goal Scored', '1st Goal', 'Own goals', 'Own goal Time']].head()

,Team,Opponent,Goal Scored,1st Goal,Own goals,Own goal Time
0,Russia,Saudi Arabia,5,12.000000,1.0,45.833333
1,Saudi Arabia,Russia,0,39.457447,1.0,45.833333
2,Egypt,Uruguay,0,39.457447,1.0,45.833333
3,Uruguay,Egypt,1,89.000000,1.0,45.833333
4,Morocco,Iran,0,39.457447,1.0,90.000000

## Preenchendo dados em valores faltantes

* Nesta base, não faz muito sentido remover os registro que possuem alguma coluna com valores faltantes;
* Também não faz muito sentido fazer interpolação;
* Uma alternativa é substituir os valores faltantes por valores que façam sentido.
* Por exemplo:
    * Podemos colocar $0$ no atributo **Own goals** e **Own goal Time**
    * Podemos colocar $-1$ na coluna **1st Goal** para representar que como o time não fez gol, então não existe o momento que aconteceu o primeiro gol;

In [36]:
df.fillna(value={'Own goals':0, 'Own goal Time':0, '1st Goal':-1}, inplace=True)
df.isnull().sum()

Date                      0
Team                      0
Opponent                  0
Goal Scored               0
Ball Possession %         0
Attempts                  0
On-Target                 0
Off-Target                0
Blocked                   0
Corners                   0
Offsides                  0
Free Kicks                0
Saves                     0
Pass Accuracy %           0
Passes                    0
Distance Covered (Kms)    0
Fouls Committed           0
Yellow Card               0
Yellow & Red              0
Red                       0
Man of the Match          0
1st Goal                  0
Round                     0
PSO                       0
Goals in PSO              0
Own goals                 0
Own goal Time             0
dtype: int64

In [37]:
df.head()

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,Yes,12.0,Group Stage,No,0,0.0,0.0
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,No,-1.0,Group Stage,No,0,0.0,0.0
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,No,-1.0,Group Stage,No,0,0.0,0.0
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,Yes,89.0,Group Stage,No,0,0.0,0.0
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,No,-1.0,Group Stage,No,0,1.0,90.0

## Codificando os atributos booleanos com valores numéricos

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 27 columns):
Date                      128 non-null object
Team                      128 non-null object
Opponent                  128 non-null object
Goal Scored               128 non-null int64
Ball Possession %         128 non-null int64
Attempts                  128 non-null int64
On-Target                 128 non-null int64
Off-Target                128 non-null int64
Blocked                   128 non-null int64
Corners                   128 non-null int64
Offsides                  128 non-null int64
Free Kicks                128 non-null int64
Saves                     128 non-null int64
Pass Accuracy %           128 non-null int64
Passes                    128 non-null int64
Distance Covered (Kms)    128 non-null int64
Fouls Committed           128 non-null int64
Yellow Card               128 non-null int64
Yellow & Red              128 non-null int64
Red                       128 non-null int64
Man of the Match          128 non-null object
1st Goal                  128 non-null float64
Round                     128 non-null object
PSO                       128 non-null object
Goals in PSO              128 non-null int64
Own goals                 128 non-null float64
Own goal Time             128 non-null float64
dtypes: float64(3), int64(18), object(6)
memory usage: 27.1+ KB

In [39]:
df['Man of the Match'] = df['Man of the Match'].map({'Yes': 1, 'No': 0})
df['PSO'] = df['PSO'].map({'Yes': 1, 'No': 0})
df

,Date,Team,Opponent,Goal Scored,Ball Possession %,Attempts,On-Target,Off-Target,Blocked,Corners,...,Yellow Card,Yellow & Red,Red,Man of the Match,1st Goal,Round,PSO,Goals in PSO,Own goals,Own goal Time
0,14-06-2018,Russia,Saudi Arabia,5,40,13,7,3,3,6,...,0,0,0,1,12.0,Group Stage,0,0,0.0,0.0
1,14-06-2018,Saudi Arabia,Russia,0,60,6,0,3,3,2,...,0,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
2,15-06-2018,Egypt,Uruguay,0,43,8,3,3,2,0,...,2,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
3,15-06-2018,Uruguay,Egypt,1,57,14,4,6,4,5,...,0,0,0,1,89.0,Group Stage,0,0,0.0,0.0
4,15-06-2018,Morocco,Iran,0,64,13,3,6,4,5,...,1,0,0,0,-1.0,Group Stage,0,0,1.0,90.0
5,15-06-2018,Iran,Morocco,1,36,8,2,5,1,2,...,3,0,0,1,90.0,Group Stage,0,0,0.0,0.0
6,15-06-2018,Portugal,Spain,3,39,8,3,2,3,4,...,1,0,0,0,4.0,Group Stage,0,0,0.0,0.0
7,15-06-2018,Spain,Portugal,3,61,12,5,5,2,5,...,1,0,0,1,24.0,Group Stage,0,0,0.0,0.0
8,16-06-2018,France,Australia,2,51,12,5,4,3,5,...,1,0,0,1,58.0,Group Stage,0,0,0.0,0.0
9,16-06-2018,Australia,France,1,49,4,1,2,1,1,...,3,0,0,0,62.0,Group Stage,0,0,1.0,81.0
10,16-06-2018,Argentina,Iceland,1,72,26,7,9,10,10,...,0,0,0,0,19.0,Group Stage,0,0,0.0,0.0
11,16-06-2018,Iceland,Argentina,1,28,9,3,5,1,2,...,0,0,0,1,23.0,Group Stage,0,0,0.0,0.0
12,16-06-2018,Peru,Denmark,0,52,18,6,7,5,3,...,1,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
13,16-06-2018,Denmark,Peru,1,48,10,3,5,2,7,...,2,0,0,1,59.0,Group Stage,0,0,0.0,0.0
14,17-06-2018,Croatia,Nigeria,2,54,11,2,7,2,6,...,2,0,0,1,32.0,Group Stage,0,0,0.0,0.0
15,17-06-2018,Nigeria,Croatia,0,46,14,2,5,7,5,...,1,0,0,0,-1.0,Group Stage,0,0,1.0,32.0
16,17-06-2018,Costa Rica,Serbia,0,50,10,3,3,4,5,...,2,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
17,17-06-2018,Serbia,Costa Rica,1,50,10,3,5,2,4,...,2,0,0,1,56.0,Group Stage,0,0,0.0,0.0
18,17-06-2018,Germany,Mexico,0,60,25,9,9,7,8,...,2,0,0,1,-1.0,Group Stage,0,0,0.0,0.0
19,17-06-2018,Mexico,Germany,1,40,12,4,6,2,1,...,2,0,0,0,35.0,Group Stage,0,0,0.0,0.0
20,17-06-2018,Brazil,Switzerland,1,52,20,4,9,7,7,...,1,0,0,1,20.0,Group Stage,0,0,0.0,0.0
21,17-06-2018,Switzerland,Brazil,1,48,6,2,4,0,2,...,3,0,0,0,50.0,Group Stage,0,0,0.0,0.0
22,18-06-2018,Sweden,Korea Republic,1,52,15,4,5,6,6,...,1,0,0,1,65.0,Group Stage,0,0,0.0,0.0
23,18-06-2018,Korea Republic,Sweden,0,48,5,0,2,3,5,...,2,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
24,18-06-2018,Belgium,Panama,3,61,15,6,7,2,9,...,3,0,0,1,47.0,Group Stage,0,0,0.0,0.0
25,18-06-2018,Panama,Belgium,0,39,6,2,4,0,3,...,5,0,0,0,-1.0,Group Stage,0,0,0.0,0.0
26,18-06-2018,Tunisia,England,1,41,6,1,3,2,2,...,0,0,0,0,11.0,Group Stage,0,0,0.0,0.0
27,18-06-2018,England,Tunisia,2,59,17,7,7,3,7,...,1,0,0,1,35.0,Group Stage,0,0,0.0,0.0
28,19-06-2018,Colombia,Japan,1,41,8,3,1,4,3,...,2,0,1,0,39.0,Group Stage,0,0,0.0,0.0
29,19-06-2018,Japan,Colombia,2,59,14,6,5,3,6,...,1,0,0,1,6.0,Group Stage,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,30-06-2018,Uruguay,Portugal,2,39,6,3,2,1,2,...,0,0,0,1,7.0,Round of 16,0,0,0.0,0.0
99,30-06-2018,Portugal,Uruguay,1,61,20,5,1,8,10,...,1,0,0,0,55.0,Round of 16,0,0,0.0,0.0
100,01-07-2018,Spain,Russia,1,75,25,9,6,10,6,...,1,0,0,0,12.0,Round of 16,1,3,0.0,0.0
101,01-07-2018,Russia,Spain,1,25,6,1,3,2,5,...,2,0,0,1,41.0,Round of 16,1,4,1.0,12.0
102,01-07-2018,Croatia,Denmark,1,54,22,7,8,7,5,...,0,0,0,1,4.0,Round of 16,1,3,0.0,0.0
103,01-07-2018,Denmark,Croatia,1,46,15,3,10,2,4,...,1,0,0,0,1.0,Round of 16,1,2,0.0,0.0
104,02-07-2018,Brazil,Mexico,2,47,21,10,7,4,8,...,2,0,0,1,51.0,Round of 16,0,0,0.0,0.0
105,02-07-2018,Mexico,Brazil,0,53,13,1,4,8,7,...,4,0,0,0,-1.0,Round of 16,0,0,0.0,0.0
106,02-07-2018,Belgium,Japan,3,56,24,8,10,6,10,...,0,0,0,1,69.0,Round of 16,0,0,0.0,0.0
107,02-07-2018,Japan,Belgium,2,44,11,4,4,3,6,...,1,0,0,0,48.0,Round of 16,0,0,0.0,0.0
108,03-07-2018,Sweden,Switzerland,1,37,12,3,6,3,3,...,1,0,0,1,66.0,Round of 16,0,0,0.0,0.0
109,03-07-2018,Switzerland,Sweden,0,63,18,4,5,9,11,...,2,0,1,0,-1.0,Round of 16,0,0,0.0,0.0
110,03-07-2018,Colombia,England,1,48,14,4,7,3,2,...,6,0,0,0,90.0,Round of 16,1,3,0.0,0.0
111,03-07-2018,England,Colombia,1,51,16,2,9,5,7,...,2,0,0,1,57.0,Round of 16,1,4,0.0,0.0
112,06-07-2018,Uruguay,France,0,42,11,4,6,1,4,...,2,0,0,0,-1.0,Quarter Finals,0,0,0.0,0.0
113,06-07-2018,France,Uruguay,2,58,11,2,7,2,3,...,2,0,0,1,40.0,Quarter Finals,0,0,0.0,0.0
114,06-07-2018,Brazil,Belgium,1,57,26,9,7,10,8,...,2,0,0,0,-1.0,Quarter Finals,0,0,1.0,13.0
115,06-07-2018,Belgium,Brazil,2,43,8,3,3,2,4,...,2,0,0,1,13.0,Quarter Finals,0,0,0.0,0.0
116,07-07-2018,Sweden,England,0,43,7,3,3,1,1,...,2,0,0,0,-1.0,Quarter Finals,0,0,0.0,0.0
117,07-07-2018,England,Sweden,2,57,12,2,4,6,6,...,1,0,0,1,30.0,Quarter Finals,0,0,0.0,0.0
118,07-07-2018,Russia,Croatia,2,38,13,7,4,2,6,...,1,0,0,0,31.0,Quarter Finals,1,3,0.0,0.0
119,07-07-2018,Croatia,Russia,2,62,17,3,10,4,8,...,4,0,0,1,39.0,Quarter Finals,1,4,0.0,0.0
120,10-07-2018,France,Belgium,1,40,19,5,8,6,4,...,2,0,0,1,51.0,Semi- Finals,0,0,0.0,0.0
121,10-07-2018,Belgium,France,0,60,9,3,5,1,5,...,3,0,0,0,-1.0,Semi- Finals,0,0,0.0,0.0
122,11-07-2018,Croatia,England,2,54,22,7,11,4,8,...,2,0,0,1,68.0,Semi- Finals,0,0,0.0,0.0
123,11-07-2018,England,Croatia,1,46,11,1,6,4,4,...,1,0,0,0,5.0,Semi- Finals,0,0,0.0,0.0
124,14-07-2018,Belgium,England,2,43,12,4,3,5,4,...,1,0,0,1,4.0,3rd Place,0,0,0.0,0.0
125,14-07-2018,England,Belgium,0,57,15,5,7,3,5,...,2,0,0,0,-1.0,3rd Place,0,0,0.0,0.0
126,15-07-2018,France,Croatia,4,39,8,6,1,1,2,...,2,0,0,1,18.0,Final,0,0,1.0,18.0
127,15-07-2018,Croatia,France,2,61,15,3,8,4,6,...,1,0,0,0,28.0,Final,0,0,0.0,0.0

### Exportando a base de dados

* Vamos salvar essas alterações, para podermos trabalhar com essa base de dados a partir de agora.

In [40]:
df.to_csv('data/FIFA_2018_Statistics_sem_NaN.csv', index=False)